language: python
  python:
    - "3.6"
os: osx
sudo: enabled
before-install:
  - sudo apt-get update
  - sudo apt-get install python3
install:
  - pip install -r requirements.txt
script: python3 test/test.py
branches:
  only:
    - master