
language: python
python:
  - "3.6"

os: 
  - linux
  - osx
  
matrix:
  allow_failures:
    - os: osx

install: "pip install -r requirements.txt"

script: cd tests && python3 -m unittest -b -v test_lexer.py && python3 -m unittest -b -v test_command_line_parser.py